# Generated by Django 4.2.6 on 2024-04-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='titile',
            new_name='title',
        ),
    ]
